<?php
return [
    'sms_user_id'=>[
        'title'=>'用户id',
        'value'=>''
    ],
    'sms_account'=>[
        'title'=>'用户账号',
        'value'=>'',
    ],
    'sms_password'=>[
        'title'=>'用户密码',
        'value'=>'',
    ],
    'sms_prefix'=>[
        'title'=>'短信签名',
        'value'=>'jshop',
    ]
];