<?php
return [
    'display' => [
        'title' => '是否显示:',
        'type' => 'radio',
        'options' => [
            '1' => '显示',
            '0' => '不显示'
        ],
        'value' => '1'
    ],
    //自定义配置
    'template'=>[
        'title'=>'模板配置',
        'value'=>[
            'create_order'=>[
                'title'=>'催付提醒',
                'data'=>[
                    [
                        'title'=>'模板ID',
                        'code'=>'template_id',
                    ],
                    [
                        'title'=>'商家名称',
                        'code'=>'seller_name',
                    ],
                    [
                        'title'=>'订单编号',
                        'code'=>'order_id',
                    ],
                    [
                        'title'=>'订单金额',
                        'code'=>'order_amount',
                    ],
                    [
                        'title'=>'温馨提示',
                        'code'=>'notice',
                    ]
                ],
            ],
            'delivery_notice'=>[
                'title'=>'订单发货',
                'data'=>[
                    [
                        'title'=>'模板ID',
                        'code'=>'template_id',
                    ],
                    [
                        'title'=>'订单号',
                        'code'=>'order_id',
                    ],
                    [
                        'title'=>'物流公司',
                        'code'=>'logistics_name',
                    ],
                    [
                        'title'=>'物流单号',
                        'code'=>'ship_no',
                    ],
                    [
                        'title'=>'收货地址',
                        'code'=>'ship_addr',
                    ],
                    [
                        'title'=>'收货人',
                        'code'=>'ship_name',
                    ],
                ],
            ],
            'refund_success'=>[
                'title'=>'订单退款',
                'data'=>[
                    [
                        'title'=>'模板ID',
                        'code'=>'template_id',
                    ],
                    [
                        'title'=>'订单编号',
                        'code'=>'source_id',
                    ],
                    [
                        'title'=>'退款金额',
                        'code'=>'money',
                    ],
                    [
                        'title'=>'退款时间',
                        'code'=>'refund_time',
                    ],
                    [
                        'title'=>'退款说明',
                        'code'=>'refund_reason',
                    ],
                    [
                        'title'=>'退款状态',
                        'code'=>'refund_status',
                    ]
                ],
            ],
        ],
    ],
];